// Code generated by protoc-gen-go.
// source: slop.proto
// DO NOT EDIT!

/*
Package voldemort is a generated protocol buffer package.

It is generated from these files:
	slop.proto
	voldemort-admin.proto
	voldemort-client.proto

It has these top-level messages:
	Slop
*/
package voldemort

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Slop struct {
	Store            *string `protobuf:"bytes,1,opt,name=store" json:"store,omitempty"`
	Operation        *string `protobuf:"bytes,2,opt,name=operation" json:"operation,omitempty"`
	Key              []byte  `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Value            []byte  `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	NodeId           *int32  `protobuf:"varint,5,opt,name=node_id" json:"node_id,omitempty"`
	Arrived          *int64  `protobuf:"varint,6,opt,name=arrived" json:"arrived,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Slop) Reset()         { *m = Slop{} }
func (m *Slop) String() string { return proto.CompactTextString(m) }
func (*Slop) ProtoMessage()    {}

func (m *Slop) GetStore() string {
	if m != nil && m.Store != nil {
		return *m.Store
	}
	return ""
}

func (m *Slop) GetOperation() string {
	if m != nil && m.Operation != nil {
		return *m.Operation
	}
	return ""
}

func (m *Slop) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Slop) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Slop) GetNodeId() int32 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *Slop) GetArrived() int64 {
	if m != nil && m.Arrived != nil {
		return *m.Arrived
	}
	return 0
}

func init() {
}
