// Code generated by protoc-gen-go.
// source: voldemort-client.proto
// DO NOT EDIT!

package voldemort

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type RequestType int32

const (
	RequestType_GET         RequestType = 0
	RequestType_GET_ALL     RequestType = 1
	RequestType_PUT         RequestType = 2
	RequestType_DELETE      RequestType = 3
	RequestType_GET_VERSION RequestType = 4
)

var RequestType_name = map[int32]string{
	0: "GET",
	1: "GET_ALL",
	2: "PUT",
	3: "DELETE",
	4: "GET_VERSION",
}
var RequestType_value = map[string]int32{
	"GET":         0,
	"GET_ALL":     1,
	"PUT":         2,
	"DELETE":      3,
	"GET_VERSION": 4,
}

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}
func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (x *RequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestType_value, data, "RequestType")
	if err != nil {
		return err
	}
	*x = RequestType(value)
	return nil
}

type ClockEntry struct {
	NodeId           *int32 `protobuf:"varint,1,req,name=node_id" json:"node_id,omitempty"`
	Version          *int64 `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ClockEntry) Reset()         { *m = ClockEntry{} }
func (m *ClockEntry) String() string { return proto.CompactTextString(m) }
func (*ClockEntry) ProtoMessage()    {}

func (m *ClockEntry) GetNodeId() int32 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *ClockEntry) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type VectorClock struct {
	Entries          []*ClockEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	Timestamp        *int64        `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *VectorClock) Reset()         { *m = VectorClock{} }
func (m *VectorClock) String() string { return proto.CompactTextString(m) }
func (*VectorClock) ProtoMessage()    {}

func (m *VectorClock) GetEntries() []*ClockEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *VectorClock) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type Versioned struct {
	Value            []byte       `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	Version          *VectorClock `protobuf:"bytes,2,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Versioned) Reset()         { *m = Versioned{} }
func (m *Versioned) String() string { return proto.CompactTextString(m) }
func (*Versioned) ProtoMessage()    {}

func (m *Versioned) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Versioned) GetVersion() *VectorClock {
	if m != nil {
		return m.Version
	}
	return nil
}

type Error struct {
	ErrorCode        *int32  `protobuf:"varint,1,req,name=error_code" json:"error_code,omitempty"`
	ErrorMessage     *string `protobuf:"bytes,2,req,name=error_message" json:"error_message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}

func (m *Error) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *Error) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

type KeyedVersions struct {
	Key              []byte       `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Versions         []*Versioned `protobuf:"bytes,2,rep,name=versions" json:"versions,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *KeyedVersions) Reset()         { *m = KeyedVersions{} }
func (m *KeyedVersions) String() string { return proto.CompactTextString(m) }
func (*KeyedVersions) ProtoMessage()    {}

func (m *KeyedVersions) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyedVersions) GetVersions() []*Versioned {
	if m != nil {
		return m.Versions
	}
	return nil
}

type GetRequest struct {
	Key              []byte `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Transforms       []byte `protobuf:"bytes,2,opt,name=transforms" json:"transforms,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetRequest) GetTransforms() []byte {
	if m != nil {
		return m.Transforms
	}
	return nil
}

type GetResponse struct {
	Versioned        []*Versioned `protobuf:"bytes,1,rep,name=versioned" json:"versioned,omitempty"`
	Error            *Error       `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}

func (m *GetResponse) GetVersioned() []*Versioned {
	if m != nil {
		return m.Versioned
	}
	return nil
}

func (m *GetResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetVersionResponse struct {
	Versions         []*VectorClock `protobuf:"bytes,1,rep,name=versions" json:"versions,omitempty"`
	Error            *Error         `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GetVersionResponse) Reset()         { *m = GetVersionResponse{} }
func (m *GetVersionResponse) String() string { return proto.CompactTextString(m) }
func (*GetVersionResponse) ProtoMessage()    {}

func (m *GetVersionResponse) GetVersions() []*VectorClock {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *GetVersionResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetAllRequest struct {
	Keys             [][]byte                         `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	Transforms       []*GetAllRequest_GetAllTransform `protobuf:"bytes,2,rep,name=transforms" json:"transforms,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}

func (m *GetAllRequest) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *GetAllRequest) GetTransforms() []*GetAllRequest_GetAllTransform {
	if m != nil {
		return m.Transforms
	}
	return nil
}

type GetAllRequest_GetAllTransform struct {
	Key              []byte `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Transform        []byte `protobuf:"bytes,2,req,name=transform" json:"transform,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetAllRequest_GetAllTransform) Reset()         { *m = GetAllRequest_GetAllTransform{} }
func (m *GetAllRequest_GetAllTransform) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest_GetAllTransform) ProtoMessage()    {}

func (m *GetAllRequest_GetAllTransform) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetAllRequest_GetAllTransform) GetTransform() []byte {
	if m != nil {
		return m.Transform
	}
	return nil
}

type GetAllResponse struct {
	Values           []*KeyedVersions `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	Error            *Error           `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GetAllResponse) Reset()         { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()    {}

func (m *GetAllResponse) GetValues() []*KeyedVersions {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *GetAllResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type PutRequest struct {
	Key              []byte     `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Versioned        *Versioned `protobuf:"bytes,2,req,name=versioned" json:"versioned,omitempty"`
	Transforms       []byte     `protobuf:"bytes,3,opt,name=transforms" json:"transforms,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}

func (m *PutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PutRequest) GetVersioned() *Versioned {
	if m != nil {
		return m.Versioned
	}
	return nil
}

func (m *PutRequest) GetTransforms() []byte {
	if m != nil {
		return m.Transforms
	}
	return nil
}

type PutResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}

func (m *PutResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DeleteRequest struct {
	Key              []byte       `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Version          *VectorClock `protobuf:"bytes,2,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}

func (m *DeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DeleteRequest) GetVersion() *VectorClock {
	if m != nil {
		return m.Version
	}
	return nil
}

type DeleteResponse struct {
	Success          *bool  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Error            *Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}

func (m *DeleteResponse) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *DeleteResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type VoldemortRequest struct {
	Type             *RequestType   `protobuf:"varint,1,req,name=type,enum=voldemort.RequestType" json:"type,omitempty"`
	ShouldRoute      *bool          `protobuf:"varint,2,req,name=should_route,def=0" json:"should_route,omitempty"`
	Store            *string        `protobuf:"bytes,3,req,name=store" json:"store,omitempty"`
	Get              *GetRequest    `protobuf:"bytes,4,opt,name=get" json:"get,omitempty"`
	GetAll           *GetAllRequest `protobuf:"bytes,5,opt,name=getAll" json:"getAll,omitempty"`
	Put              *PutRequest    `protobuf:"bytes,6,opt,name=put" json:"put,omitempty"`
	Delete           *DeleteRequest `protobuf:"bytes,7,opt,name=delete" json:"delete,omitempty"`
	RequestRouteType *int32         `protobuf:"varint,8,opt,name=requestRouteType" json:"requestRouteType,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *VoldemortRequest) Reset()         { *m = VoldemortRequest{} }
func (m *VoldemortRequest) String() string { return proto.CompactTextString(m) }
func (*VoldemortRequest) ProtoMessage()    {}

const Default_VoldemortRequest_ShouldRoute bool = false

func (m *VoldemortRequest) GetType() RequestType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RequestType_GET
}

func (m *VoldemortRequest) GetShouldRoute() bool {
	if m != nil && m.ShouldRoute != nil {
		return *m.ShouldRoute
	}
	return Default_VoldemortRequest_ShouldRoute
}

func (m *VoldemortRequest) GetStore() string {
	if m != nil && m.Store != nil {
		return *m.Store
	}
	return ""
}

func (m *VoldemortRequest) GetGet() *GetRequest {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *VoldemortRequest) GetGetAll() *GetAllRequest {
	if m != nil {
		return m.GetAll
	}
	return nil
}

func (m *VoldemortRequest) GetPut() *PutRequest {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *VoldemortRequest) GetDelete() *DeleteRequest {
	if m != nil {
		return m.Delete
	}
	return nil
}

func (m *VoldemortRequest) GetRequestRouteType() int32 {
	if m != nil && m.RequestRouteType != nil {
		return *m.RequestRouteType
	}
	return 0
}

func init() {
	proto.RegisterEnum("voldemort.RequestType", RequestType_name, RequestType_value)
}
