// Code generated by protoc-gen-go.
// source: voldemort-admin.proto
// DO NOT EDIT!

package voldemort

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type AdminRequestType int32

const (
	AdminRequestType_GET_METADATA               AdminRequestType = 0
	AdminRequestType_UPDATE_METADATA            AdminRequestType = 1
	AdminRequestType_UPDATE_PARTITION_ENTRIES   AdminRequestType = 2
	AdminRequestType_FETCH_PARTITION_ENTRIES    AdminRequestType = 3
	AdminRequestType_DELETE_PARTITION_ENTRIES   AdminRequestType = 4
	AdminRequestType_INITIATE_FETCH_AND_UPDATE  AdminRequestType = 5
	AdminRequestType_ASYNC_OPERATION_STATUS     AdminRequestType = 6
	AdminRequestType_INITIATE_REBALANCE_NODE    AdminRequestType = 7
	AdminRequestType_ASYNC_OPERATION_STOP       AdminRequestType = 8
	AdminRequestType_ASYNC_OPERATION_LIST       AdminRequestType = 9
	AdminRequestType_TRUNCATE_ENTRIES           AdminRequestType = 10
	AdminRequestType_ADD_STORE                  AdminRequestType = 11
	AdminRequestType_DELETE_STORE               AdminRequestType = 12
	AdminRequestType_FETCH_STORE                AdminRequestType = 13
	AdminRequestType_SWAP_STORE                 AdminRequestType = 14
	AdminRequestType_ROLLBACK_STORE             AdminRequestType = 15
	AdminRequestType_GET_RO_MAX_VERSION_DIR     AdminRequestType = 16
	AdminRequestType_GET_RO_CURRENT_VERSION_DIR AdminRequestType = 17
	AdminRequestType_FETCH_PARTITION_FILES      AdminRequestType = 18
	AdminRequestType_UPDATE_SLOP_ENTRIES        AdminRequestType = 20
	AdminRequestType_FAILED_FETCH_STORE         AdminRequestType = 22
	AdminRequestType_GET_RO_STORAGE_FORMAT      AdminRequestType = 23
	AdminRequestType_REBALANCE_STATE_CHANGE     AdminRequestType = 24
	AdminRequestType_REPAIR_JOB                 AdminRequestType = 25
	// INITIATE_REBALANCE_NODE_ON_DONOR = 26;
	AdminRequestType_DELETE_STORE_REBALANCE_STATE AdminRequestType = 27
	AdminRequestType_NATIVE_BACKUP                AdminRequestType = 28
	AdminRequestType_RESERVE_MEMORY               AdminRequestType = 29
	AdminRequestType_PRUNE_JOB                    AdminRequestType = 30
)

var AdminRequestType_name = map[int32]string{
	0:  "GET_METADATA",
	1:  "UPDATE_METADATA",
	2:  "UPDATE_PARTITION_ENTRIES",
	3:  "FETCH_PARTITION_ENTRIES",
	4:  "DELETE_PARTITION_ENTRIES",
	5:  "INITIATE_FETCH_AND_UPDATE",
	6:  "ASYNC_OPERATION_STATUS",
	7:  "INITIATE_REBALANCE_NODE",
	8:  "ASYNC_OPERATION_STOP",
	9:  "ASYNC_OPERATION_LIST",
	10: "TRUNCATE_ENTRIES",
	11: "ADD_STORE",
	12: "DELETE_STORE",
	13: "FETCH_STORE",
	14: "SWAP_STORE",
	15: "ROLLBACK_STORE",
	16: "GET_RO_MAX_VERSION_DIR",
	17: "GET_RO_CURRENT_VERSION_DIR",
	18: "FETCH_PARTITION_FILES",
	20: "UPDATE_SLOP_ENTRIES",
	22: "FAILED_FETCH_STORE",
	23: "GET_RO_STORAGE_FORMAT",
	24: "REBALANCE_STATE_CHANGE",
	25: "REPAIR_JOB",
	27: "DELETE_STORE_REBALANCE_STATE",
	28: "NATIVE_BACKUP",
	29: "RESERVE_MEMORY",
	30: "PRUNE_JOB",
}
var AdminRequestType_value = map[string]int32{
	"GET_METADATA":                 0,
	"UPDATE_METADATA":              1,
	"UPDATE_PARTITION_ENTRIES":     2,
	"FETCH_PARTITION_ENTRIES":      3,
	"DELETE_PARTITION_ENTRIES":     4,
	"INITIATE_FETCH_AND_UPDATE":    5,
	"ASYNC_OPERATION_STATUS":       6,
	"INITIATE_REBALANCE_NODE":      7,
	"ASYNC_OPERATION_STOP":         8,
	"ASYNC_OPERATION_LIST":         9,
	"TRUNCATE_ENTRIES":             10,
	"ADD_STORE":                    11,
	"DELETE_STORE":                 12,
	"FETCH_STORE":                  13,
	"SWAP_STORE":                   14,
	"ROLLBACK_STORE":               15,
	"GET_RO_MAX_VERSION_DIR":       16,
	"GET_RO_CURRENT_VERSION_DIR":   17,
	"FETCH_PARTITION_FILES":        18,
	"UPDATE_SLOP_ENTRIES":          20,
	"FAILED_FETCH_STORE":           22,
	"GET_RO_STORAGE_FORMAT":        23,
	"REBALANCE_STATE_CHANGE":       24,
	"REPAIR_JOB":                   25,
	"DELETE_STORE_REBALANCE_STATE": 27,
	"NATIVE_BACKUP":                28,
	"RESERVE_MEMORY":               29,
	"PRUNE_JOB":                    30,
}

func (x AdminRequestType) Enum() *AdminRequestType {
	p := new(AdminRequestType)
	*p = x
	return p
}
func (x AdminRequestType) String() string {
	return proto.EnumName(AdminRequestType_name, int32(x))
}
func (x *AdminRequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AdminRequestType_value, data, "AdminRequestType")
	if err != nil {
		return err
	}
	*x = AdminRequestType(value)
	return nil
}

type GetMetadataRequest struct {
	Key              []byte `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetMetadataRequest) Reset()         { *m = GetMetadataRequest{} }
func (m *GetMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*GetMetadataRequest) ProtoMessage()    {}

func (m *GetMetadataRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetMetadataResponse struct {
	Version          *Versioned `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Error            *Error     `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *GetMetadataResponse) Reset()         { *m = GetMetadataResponse{} }
func (m *GetMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*GetMetadataResponse) ProtoMessage()    {}

func (m *GetMetadataResponse) GetVersion() *Versioned {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *GetMetadataResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UpdateMetadataRequest struct {
	Key              []byte     `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Versioned        *Versioned `protobuf:"bytes,2,req,name=versioned" json:"versioned,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *UpdateMetadataRequest) Reset()         { *m = UpdateMetadataRequest{} }
func (m *UpdateMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataRequest) ProtoMessage()    {}

func (m *UpdateMetadataRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *UpdateMetadataRequest) GetVersioned() *Versioned {
	if m != nil {
		return m.Versioned
	}
	return nil
}

type UpdateMetadataResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UpdateMetadataResponse) Reset()         { *m = UpdateMetadataResponse{} }
func (m *UpdateMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataResponse) ProtoMessage()    {}

func (m *UpdateMetadataResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type FileEntry struct {
	FileName         *string `protobuf:"bytes,1,req,name=file_name" json:"file_name,omitempty"`
	FileSizeBytes    *int64  `protobuf:"varint,2,req,name=file_size_bytes" json:"file_size_bytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FileEntry) Reset()         { *m = FileEntry{} }
func (m *FileEntry) String() string { return proto.CompactTextString(m) }
func (*FileEntry) ProtoMessage()    {}

func (m *FileEntry) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *FileEntry) GetFileSizeBytes() int64 {
	if m != nil && m.FileSizeBytes != nil {
		return *m.FileSizeBytes
	}
	return 0
}

type PartitionEntry struct {
	Key              []byte     `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Versioned        *Versioned `protobuf:"bytes,2,req,name=versioned" json:"versioned,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *PartitionEntry) Reset()         { *m = PartitionEntry{} }
func (m *PartitionEntry) String() string { return proto.CompactTextString(m) }
func (*PartitionEntry) ProtoMessage()    {}

func (m *PartitionEntry) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PartitionEntry) GetVersioned() *Versioned {
	if m != nil {
		return m.Versioned
	}
	return nil
}

type UpdatePartitionEntriesRequest struct {
	Store               *string          `protobuf:"bytes,1,req,name=store" json:"store,omitempty"`
	PartitionEntry      *PartitionEntry  `protobuf:"bytes,2,req,name=partition_entry" json:"partition_entry,omitempty"`
	Filter              *VoldemortFilter `protobuf:"bytes,3,opt,name=filter" json:"filter,omitempty"`
	OverwriteIfLatestTs *bool            `protobuf:"varint,4,opt,name=overwriteIfLatestTs" json:"overwriteIfLatestTs,omitempty"`
	XXX_unrecognized    []byte           `json:"-"`
}

func (m *UpdatePartitionEntriesRequest) Reset()         { *m = UpdatePartitionEntriesRequest{} }
func (m *UpdatePartitionEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePartitionEntriesRequest) ProtoMessage()    {}

func (m *UpdatePartitionEntriesRequest) GetStore() string {
	if m != nil && m.Store != nil {
		return *m.Store
	}
	return ""
}

func (m *UpdatePartitionEntriesRequest) GetPartitionEntry() *PartitionEntry {
	if m != nil {
		return m.PartitionEntry
	}
	return nil
}

func (m *UpdatePartitionEntriesRequest) GetFilter() *VoldemortFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *UpdatePartitionEntriesRequest) GetOverwriteIfLatestTs() bool {
	if m != nil && m.OverwriteIfLatestTs != nil {
		return *m.OverwriteIfLatestTs
	}
	return false
}

type UpdatePartitionEntriesResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UpdatePartitionEntriesResponse) Reset()         { *m = UpdatePartitionEntriesResponse{} }
func (m *UpdatePartitionEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePartitionEntriesResponse) ProtoMessage()    {}

func (m *UpdatePartitionEntriesResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type VoldemortFilter struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VoldemortFilter) Reset()         { *m = VoldemortFilter{} }
func (m *VoldemortFilter) String() string { return proto.CompactTextString(m) }
func (*VoldemortFilter) ProtoMessage()    {}

func (m *VoldemortFilter) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *VoldemortFilter) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateSlopEntriesRequest struct {
	Store            *string      `protobuf:"bytes,1,req,name=store" json:"store,omitempty"`
	Key              []byte       `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Version          *VectorClock `protobuf:"bytes,3,req,name=version" json:"version,omitempty"`
	RequestType      *RequestType `protobuf:"varint,4,req,name=request_type,enum=voldemort.RequestType" json:"request_type,omitempty"`
	Value            []byte       `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
	Transform        []byte       `protobuf:"bytes,6,opt,name=transform" json:"transform,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *UpdateSlopEntriesRequest) Reset()         { *m = UpdateSlopEntriesRequest{} }
func (m *UpdateSlopEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSlopEntriesRequest) ProtoMessage()    {}

func (m *UpdateSlopEntriesRequest) GetStore() string {
	if m != nil && m.Store != nil {
		return *m.Store
	}
	return ""
}

func (m *UpdateSlopEntriesRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *UpdateSlopEntriesRequest) GetVersion() *VectorClock {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *UpdateSlopEntriesRequest) GetRequestType() RequestType {
	if m != nil && m.RequestType != nil {
		return *m.RequestType
	}
	return RequestType_GET
}

func (m *UpdateSlopEntriesRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *UpdateSlopEntriesRequest) GetTransform() []byte {
	if m != nil {
		return m.Transform
	}
	return nil
}

type UpdateSlopEntriesResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UpdateSlopEntriesResponse) Reset()         { *m = UpdateSlopEntriesResponse{} }
func (m *UpdateSlopEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSlopEntriesResponse) ProtoMessage()    {}

func (m *UpdateSlopEntriesResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type FetchPartitionFilesRequest struct {
	StoreName        *string `protobuf:"bytes,1,req,name=store_name" json:"store_name,omitempty"`
	PartitionIds     []int32 `protobuf:"varint,2,rep,name=partition_ids" json:"partition_ids,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FetchPartitionFilesRequest) Reset()         { *m = FetchPartitionFilesRequest{} }
func (m *FetchPartitionFilesRequest) String() string { return proto.CompactTextString(m) }
func (*FetchPartitionFilesRequest) ProtoMessage()    {}

func (m *FetchPartitionFilesRequest) GetStoreName() string {
	if m != nil && m.StoreName != nil {
		return *m.StoreName
	}
	return ""
}

func (m *FetchPartitionFilesRequest) GetPartitionIds() []int32 {
	if m != nil {
		return m.PartitionIds
	}
	return nil
}

type FetchPartitionEntriesRequest struct {
	PartitionIds                     []int32          `protobuf:"varint,1,rep,name=partition_ids" json:"partition_ids,omitempty"`
	Store                            *string          `protobuf:"bytes,2,req,name=store" json:"store,omitempty"`
	Filter                           *VoldemortFilter `protobuf:"bytes,3,opt,name=filter" json:"filter,omitempty"`
	FetchValues                      *bool            `protobuf:"varint,4,opt,name=fetch_values" json:"fetch_values,omitempty"`
	OBSOLETE__DO_NOT_USE_SkipRecords *int64           `protobuf:"varint,5,opt,name=OBSOLETE__DO_NOT_USE__skip_records" json:"OBSOLETE__DO_NOT_USE__skip_records,omitempty"`
	InitialCluster                   *string          `protobuf:"bytes,6,opt,name=initial_cluster" json:"initial_cluster,omitempty"`
	FetchOrphaned                    *bool            `protobuf:"varint,7,opt,name=fetch_orphaned" json:"fetch_orphaned,omitempty"`
	RecordsPerPartition              *int64           `protobuf:"varint,8,opt,name=records_per_partition" json:"records_per_partition,omitempty"`
	XXX_unrecognized                 []byte           `json:"-"`
}

func (m *FetchPartitionEntriesRequest) Reset()         { *m = FetchPartitionEntriesRequest{} }
func (m *FetchPartitionEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*FetchPartitionEntriesRequest) ProtoMessage()    {}

func (m *FetchPartitionEntriesRequest) GetPartitionIds() []int32 {
	if m != nil {
		return m.PartitionIds
	}
	return nil
}

func (m *FetchPartitionEntriesRequest) GetStore() string {
	if m != nil && m.Store != nil {
		return *m.Store
	}
	return ""
}

func (m *FetchPartitionEntriesRequest) GetFilter() *VoldemortFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *FetchPartitionEntriesRequest) GetFetchValues() bool {
	if m != nil && m.FetchValues != nil {
		return *m.FetchValues
	}
	return false
}

func (m *FetchPartitionEntriesRequest) GetOBSOLETE__DO_NOT_USE_SkipRecords() int64 {
	if m != nil && m.OBSOLETE__DO_NOT_USE_SkipRecords != nil {
		return *m.OBSOLETE__DO_NOT_USE_SkipRecords
	}
	return 0
}

func (m *FetchPartitionEntriesRequest) GetInitialCluster() string {
	if m != nil && m.InitialCluster != nil {
		return *m.InitialCluster
	}
	return ""
}

func (m *FetchPartitionEntriesRequest) GetFetchOrphaned() bool {
	if m != nil && m.FetchOrphaned != nil {
		return *m.FetchOrphaned
	}
	return false
}

func (m *FetchPartitionEntriesRequest) GetRecordsPerPartition() int64 {
	if m != nil && m.RecordsPerPartition != nil {
		return *m.RecordsPerPartition
	}
	return 0
}

type FetchPartitionEntriesResponse struct {
	PartitionEntry   *PartitionEntry `protobuf:"bytes,1,opt,name=partition_entry" json:"partition_entry,omitempty"`
	Key              []byte          `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Error            *Error          `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *FetchPartitionEntriesResponse) Reset()         { *m = FetchPartitionEntriesResponse{} }
func (m *FetchPartitionEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*FetchPartitionEntriesResponse) ProtoMessage()    {}

func (m *FetchPartitionEntriesResponse) GetPartitionEntry() *PartitionEntry {
	if m != nil {
		return m.PartitionEntry
	}
	return nil
}

func (m *FetchPartitionEntriesResponse) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *FetchPartitionEntriesResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DeletePartitionEntriesRequest struct {
	Store            *string          `protobuf:"bytes,1,req,name=store" json:"store,omitempty"`
	PartitionIds     []int32          `protobuf:"varint,2,rep,name=partition_ids" json:"partition_ids,omitempty"`
	Filter           *VoldemortFilter `protobuf:"bytes,3,opt,name=filter" json:"filter,omitempty"`
	InitialCluster   *string          `protobuf:"bytes,4,opt,name=initial_cluster" json:"initial_cluster,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *DeletePartitionEntriesRequest) Reset()         { *m = DeletePartitionEntriesRequest{} }
func (m *DeletePartitionEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePartitionEntriesRequest) ProtoMessage()    {}

func (m *DeletePartitionEntriesRequest) GetStore() string {
	if m != nil && m.Store != nil {
		return *m.Store
	}
	return ""
}

func (m *DeletePartitionEntriesRequest) GetPartitionIds() []int32 {
	if m != nil {
		return m.PartitionIds
	}
	return nil
}

func (m *DeletePartitionEntriesRequest) GetFilter() *VoldemortFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *DeletePartitionEntriesRequest) GetInitialCluster() string {
	if m != nil && m.InitialCluster != nil {
		return *m.InitialCluster
	}
	return ""
}

type DeletePartitionEntriesResponse struct {
	Count            *int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	Error            *Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeletePartitionEntriesResponse) Reset()         { *m = DeletePartitionEntriesResponse{} }
func (m *DeletePartitionEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePartitionEntriesResponse) ProtoMessage()    {}

func (m *DeletePartitionEntriesResponse) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *DeletePartitionEntriesResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type InitiateFetchAndUpdateRequest struct {
	NodeId                        *int32           `protobuf:"varint,1,req,name=node_id" json:"node_id,omitempty"`
	Store                         *string          `protobuf:"bytes,2,req,name=store" json:"store,omitempty"`
	Filter                        *VoldemortFilter `protobuf:"bytes,3,opt,name=filter" json:"filter,omitempty"`
	PartitionIds                  []int32          `protobuf:"varint,4,rep,name=partition_ids" json:"partition_ids,omitempty"`
	InitialCluster                *string          `protobuf:"bytes,5,opt,name=initial_cluster" json:"initial_cluster,omitempty"`
	OBSOLETE__DO_NOT_USE_Optimize *bool            `protobuf:"varint,6,opt,name=OBSOLETE__DO_NOT_USE__optimize" json:"OBSOLETE__DO_NOT_USE__optimize,omitempty"`
	XXX_unrecognized              []byte           `json:"-"`
}

func (m *InitiateFetchAndUpdateRequest) Reset()         { *m = InitiateFetchAndUpdateRequest{} }
func (m *InitiateFetchAndUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*InitiateFetchAndUpdateRequest) ProtoMessage()    {}

func (m *InitiateFetchAndUpdateRequest) GetNodeId() int32 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *InitiateFetchAndUpdateRequest) GetStore() string {
	if m != nil && m.Store != nil {
		return *m.Store
	}
	return ""
}

func (m *InitiateFetchAndUpdateRequest) GetFilter() *VoldemortFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *InitiateFetchAndUpdateRequest) GetPartitionIds() []int32 {
	if m != nil {
		return m.PartitionIds
	}
	return nil
}

func (m *InitiateFetchAndUpdateRequest) GetInitialCluster() string {
	if m != nil && m.InitialCluster != nil {
		return *m.InitialCluster
	}
	return ""
}

func (m *InitiateFetchAndUpdateRequest) GetOBSOLETE__DO_NOT_USE_Optimize() bool {
	if m != nil && m.OBSOLETE__DO_NOT_USE_Optimize != nil {
		return *m.OBSOLETE__DO_NOT_USE_Optimize
	}
	return false
}

type AsyncOperationStatusRequest struct {
	RequestId        *int32 `protobuf:"varint,1,req,name=request_id" json:"request_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AsyncOperationStatusRequest) Reset()         { *m = AsyncOperationStatusRequest{} }
func (m *AsyncOperationStatusRequest) String() string { return proto.CompactTextString(m) }
func (*AsyncOperationStatusRequest) ProtoMessage()    {}

func (m *AsyncOperationStatusRequest) GetRequestId() int32 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

type AsyncOperationStopRequest struct {
	RequestId        *int32 `protobuf:"varint,1,req,name=request_id" json:"request_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AsyncOperationStopRequest) Reset()         { *m = AsyncOperationStopRequest{} }
func (m *AsyncOperationStopRequest) String() string { return proto.CompactTextString(m) }
func (*AsyncOperationStopRequest) ProtoMessage()    {}

func (m *AsyncOperationStopRequest) GetRequestId() int32 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

type AsyncOperationStopResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AsyncOperationStopResponse) Reset()         { *m = AsyncOperationStopResponse{} }
func (m *AsyncOperationStopResponse) String() string { return proto.CompactTextString(m) }
func (*AsyncOperationStopResponse) ProtoMessage()    {}

func (m *AsyncOperationStopResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type AsyncOperationListRequest struct {
	ShowComplete     *bool  `protobuf:"varint,2,req,name=show_complete" json:"show_complete,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AsyncOperationListRequest) Reset()         { *m = AsyncOperationListRequest{} }
func (m *AsyncOperationListRequest) String() string { return proto.CompactTextString(m) }
func (*AsyncOperationListRequest) ProtoMessage()    {}

func (m *AsyncOperationListRequest) GetShowComplete() bool {
	if m != nil && m.ShowComplete != nil {
		return *m.ShowComplete
	}
	return false
}

type AsyncOperationListResponse struct {
	RequestIds       []int32 `protobuf:"varint,1,rep,name=request_ids" json:"request_ids,omitempty"`
	Error            *Error  `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AsyncOperationListResponse) Reset()         { *m = AsyncOperationListResponse{} }
func (m *AsyncOperationListResponse) String() string { return proto.CompactTextString(m) }
func (*AsyncOperationListResponse) ProtoMessage()    {}

func (m *AsyncOperationListResponse) GetRequestIds() []int32 {
	if m != nil {
		return m.RequestIds
	}
	return nil
}

func (m *AsyncOperationListResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type PartitionTuple struct {
	ReplicaType      *int32  `protobuf:"varint,1,req,name=replica_type" json:"replica_type,omitempty"`
	Partitions       []int32 `protobuf:"varint,2,rep,name=partitions" json:"partitions,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PartitionTuple) Reset()         { *m = PartitionTuple{} }
func (m *PartitionTuple) String() string { return proto.CompactTextString(m) }
func (*PartitionTuple) ProtoMessage()    {}

func (m *PartitionTuple) GetReplicaType() int32 {
	if m != nil && m.ReplicaType != nil {
		return *m.ReplicaType
	}
	return 0
}

func (m *PartitionTuple) GetPartitions() []int32 {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type PerStorePartitionTuple struct {
	StoreName          *string           `protobuf:"bytes,1,req,name=store_name" json:"store_name,omitempty"`
	ReplicaToPartition []*PartitionTuple `protobuf:"bytes,2,rep,name=replica_to_partition" json:"replica_to_partition,omitempty"`
	XXX_unrecognized   []byte            `json:"-"`
}

func (m *PerStorePartitionTuple) Reset()         { *m = PerStorePartitionTuple{} }
func (m *PerStorePartitionTuple) String() string { return proto.CompactTextString(m) }
func (*PerStorePartitionTuple) ProtoMessage()    {}

func (m *PerStorePartitionTuple) GetStoreName() string {
	if m != nil && m.StoreName != nil {
		return *m.StoreName
	}
	return ""
}

func (m *PerStorePartitionTuple) GetReplicaToPartition() []*PartitionTuple {
	if m != nil {
		return m.ReplicaToPartition
	}
	return nil
}

type RebalancePartitionInfoMap struct {
	StealerId                    *int32                    `protobuf:"varint,1,req,name=stealer_id" json:"stealer_id,omitempty"`
	DonorId                      *int32                    `protobuf:"varint,2,req,name=donor_id" json:"donor_id,omitempty"`
	OBSOLETE__DO_NOT_USE_Attempt *int32                    `protobuf:"varint,3,opt,name=OBSOLETE__DO_NOT_USE__attempt" json:"OBSOLETE__DO_NOT_USE__attempt,omitempty"`
	ReplicaToAddPartition        []*PerStorePartitionTuple `protobuf:"bytes,4,rep,name=replica_to_add_partition" json:"replica_to_add_partition,omitempty"`
	ReplicaToDeletePartition     []*PerStorePartitionTuple `protobuf:"bytes,5,rep,name=replica_to_delete_partition" json:"replica_to_delete_partition,omitempty"`
	InitialCluster               *string                   `protobuf:"bytes,6,req,name=initial_cluster" json:"initial_cluster,omitempty"`
	XXX_unrecognized             []byte                    `json:"-"`
}

func (m *RebalancePartitionInfoMap) Reset()         { *m = RebalancePartitionInfoMap{} }
func (m *RebalancePartitionInfoMap) String() string { return proto.CompactTextString(m) }
func (*RebalancePartitionInfoMap) ProtoMessage()    {}

func (m *RebalancePartitionInfoMap) GetStealerId() int32 {
	if m != nil && m.StealerId != nil {
		return *m.StealerId
	}
	return 0
}

func (m *RebalancePartitionInfoMap) GetDonorId() int32 {
	if m != nil && m.DonorId != nil {
		return *m.DonorId
	}
	return 0
}

func (m *RebalancePartitionInfoMap) GetOBSOLETE__DO_NOT_USE_Attempt() int32 {
	if m != nil && m.OBSOLETE__DO_NOT_USE_Attempt != nil {
		return *m.OBSOLETE__DO_NOT_USE_Attempt
	}
	return 0
}

func (m *RebalancePartitionInfoMap) GetReplicaToAddPartition() []*PerStorePartitionTuple {
	if m != nil {
		return m.ReplicaToAddPartition
	}
	return nil
}

func (m *RebalancePartitionInfoMap) GetReplicaToDeletePartition() []*PerStorePartitionTuple {
	if m != nil {
		return m.ReplicaToDeletePartition
	}
	return nil
}

func (m *RebalancePartitionInfoMap) GetInitialCluster() string {
	if m != nil && m.InitialCluster != nil {
		return *m.InitialCluster
	}
	return ""
}

type StoreToPartitionsIds struct {
	StoreName        *string `protobuf:"bytes,1,req,name=store_name" json:"store_name,omitempty"`
	PartitionIds     []int32 `protobuf:"varint,2,rep,name=partition_ids" json:"partition_ids,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StoreToPartitionsIds) Reset()         { *m = StoreToPartitionsIds{} }
func (m *StoreToPartitionsIds) String() string { return proto.CompactTextString(m) }
func (*StoreToPartitionsIds) ProtoMessage()    {}

func (m *StoreToPartitionsIds) GetStoreName() string {
	if m != nil && m.StoreName != nil {
		return *m.StoreName
	}
	return ""
}

func (m *StoreToPartitionsIds) GetPartitionIds() []int32 {
	if m != nil {
		return m.PartitionIds
	}
	return nil
}

type RebalanceTaskInfoMap struct {
	StealerId            *int32                  `protobuf:"varint,1,req,name=stealer_id" json:"stealer_id,omitempty"`
	DonorId              *int32                  `protobuf:"varint,2,req,name=donor_id" json:"donor_id,omitempty"`
	PerStorePartitionIds []*StoreToPartitionsIds `protobuf:"bytes,3,rep,name=per_store_partition_ids" json:"per_store_partition_ids,omitempty"`
	InitialCluster       *string                 `protobuf:"bytes,4,req,name=initial_cluster" json:"initial_cluster,omitempty"`
	XXX_unrecognized     []byte                  `json:"-"`
}

func (m *RebalanceTaskInfoMap) Reset()         { *m = RebalanceTaskInfoMap{} }
func (m *RebalanceTaskInfoMap) String() string { return proto.CompactTextString(m) }
func (*RebalanceTaskInfoMap) ProtoMessage()    {}

func (m *RebalanceTaskInfoMap) GetStealerId() int32 {
	if m != nil && m.StealerId != nil {
		return *m.StealerId
	}
	return 0
}

func (m *RebalanceTaskInfoMap) GetDonorId() int32 {
	if m != nil && m.DonorId != nil {
		return *m.DonorId
	}
	return 0
}

func (m *RebalanceTaskInfoMap) GetPerStorePartitionIds() []*StoreToPartitionsIds {
	if m != nil {
		return m.PerStorePartitionIds
	}
	return nil
}

func (m *RebalanceTaskInfoMap) GetInitialCluster() string {
	if m != nil && m.InitialCluster != nil {
		return *m.InitialCluster
	}
	return ""
}

type InitiateRebalanceNodeRequest struct {
	RebalanceTaskInfo *RebalanceTaskInfoMap `protobuf:"bytes,1,req,name=rebalance_task_info" json:"rebalance_task_info,omitempty"`
	XXX_unrecognized  []byte                `json:"-"`
}

func (m *InitiateRebalanceNodeRequest) Reset()         { *m = InitiateRebalanceNodeRequest{} }
func (m *InitiateRebalanceNodeRequest) String() string { return proto.CompactTextString(m) }
func (*InitiateRebalanceNodeRequest) ProtoMessage()    {}

func (m *InitiateRebalanceNodeRequest) GetRebalanceTaskInfo() *RebalanceTaskInfoMap {
	if m != nil {
		return m.RebalanceTaskInfo
	}
	return nil
}

type InitiateRebalanceNodeOnDonorRequest struct {
	RebalancePartitionInfo []*RebalancePartitionInfoMap `protobuf:"bytes,1,rep,name=rebalance_partition_info" json:"rebalance_partition_info,omitempty"`
	XXX_unrecognized       []byte                       `json:"-"`
}

func (m *InitiateRebalanceNodeOnDonorRequest) Reset()         { *m = InitiateRebalanceNodeOnDonorRequest{} }
func (m *InitiateRebalanceNodeOnDonorRequest) String() string { return proto.CompactTextString(m) }
func (*InitiateRebalanceNodeOnDonorRequest) ProtoMessage()    {}

func (m *InitiateRebalanceNodeOnDonorRequest) GetRebalancePartitionInfo() []*RebalancePartitionInfoMap {
	if m != nil {
		return m.RebalancePartitionInfo
	}
	return nil
}

type AsyncOperationStatusResponse struct {
	RequestId        *int32  `protobuf:"varint,1,opt,name=request_id" json:"request_id,omitempty"`
	Description      *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Status           *string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	Complete         *bool   `protobuf:"varint,4,opt,name=complete" json:"complete,omitempty"`
	Error            *Error  `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AsyncOperationStatusResponse) Reset()         { *m = AsyncOperationStatusResponse{} }
func (m *AsyncOperationStatusResponse) String() string { return proto.CompactTextString(m) }
func (*AsyncOperationStatusResponse) ProtoMessage()    {}

func (m *AsyncOperationStatusResponse) GetRequestId() int32 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *AsyncOperationStatusResponse) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *AsyncOperationStatusResponse) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *AsyncOperationStatusResponse) GetComplete() bool {
	if m != nil && m.Complete != nil {
		return *m.Complete
	}
	return false
}

func (m *AsyncOperationStatusResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type TruncateEntriesRequest struct {
	Store            *string `protobuf:"bytes,1,req,name=store" json:"store,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TruncateEntriesRequest) Reset()         { *m = TruncateEntriesRequest{} }
func (m *TruncateEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*TruncateEntriesRequest) ProtoMessage()    {}

func (m *TruncateEntriesRequest) GetStore() string {
	if m != nil && m.Store != nil {
		return *m.Store
	}
	return ""
}

type TruncateEntriesResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TruncateEntriesResponse) Reset()         { *m = TruncateEntriesResponse{} }
func (m *TruncateEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*TruncateEntriesResponse) ProtoMessage()    {}

func (m *TruncateEntriesResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type AddStoreRequest struct {
	StoreDefinition  *string `protobuf:"bytes,1,req,name=storeDefinition" json:"storeDefinition,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddStoreRequest) Reset()         { *m = AddStoreRequest{} }
func (m *AddStoreRequest) String() string { return proto.CompactTextString(m) }
func (*AddStoreRequest) ProtoMessage()    {}

func (m *AddStoreRequest) GetStoreDefinition() string {
	if m != nil && m.StoreDefinition != nil {
		return *m.StoreDefinition
	}
	return ""
}

type AddStoreResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AddStoreResponse) Reset()         { *m = AddStoreResponse{} }
func (m *AddStoreResponse) String() string { return proto.CompactTextString(m) }
func (*AddStoreResponse) ProtoMessage()    {}

func (m *AddStoreResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DeleteStoreRequest struct {
	StoreName        *string `protobuf:"bytes,1,req,name=storeName" json:"storeName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteStoreRequest) Reset()         { *m = DeleteStoreRequest{} }
func (m *DeleteStoreRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStoreRequest) ProtoMessage()    {}

func (m *DeleteStoreRequest) GetStoreName() string {
	if m != nil && m.StoreName != nil {
		return *m.StoreName
	}
	return ""
}

type DeleteStoreResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteStoreResponse) Reset()         { *m = DeleteStoreResponse{} }
func (m *DeleteStoreResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteStoreResponse) ProtoMessage()    {}

func (m *DeleteStoreResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type FetchStoreRequest struct {
	StoreName        *string `protobuf:"bytes,1,req,name=store_name" json:"store_name,omitempty"`
	StoreDir         *string `protobuf:"bytes,2,req,name=store_dir" json:"store_dir,omitempty"`
	PushVersion      *int64  `protobuf:"varint,3,opt,name=push_version" json:"push_version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FetchStoreRequest) Reset()         { *m = FetchStoreRequest{} }
func (m *FetchStoreRequest) String() string { return proto.CompactTextString(m) }
func (*FetchStoreRequest) ProtoMessage()    {}

func (m *FetchStoreRequest) GetStoreName() string {
	if m != nil && m.StoreName != nil {
		return *m.StoreName
	}
	return ""
}

func (m *FetchStoreRequest) GetStoreDir() string {
	if m != nil && m.StoreDir != nil {
		return *m.StoreDir
	}
	return ""
}

func (m *FetchStoreRequest) GetPushVersion() int64 {
	if m != nil && m.PushVersion != nil {
		return *m.PushVersion
	}
	return 0
}

type SwapStoreRequest struct {
	StoreName        *string `protobuf:"bytes,1,req,name=store_name" json:"store_name,omitempty"`
	StoreDir         *string `protobuf:"bytes,2,req,name=store_dir" json:"store_dir,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SwapStoreRequest) Reset()         { *m = SwapStoreRequest{} }
func (m *SwapStoreRequest) String() string { return proto.CompactTextString(m) }
func (*SwapStoreRequest) ProtoMessage()    {}

func (m *SwapStoreRequest) GetStoreName() string {
	if m != nil && m.StoreName != nil {
		return *m.StoreName
	}
	return ""
}

func (m *SwapStoreRequest) GetStoreDir() string {
	if m != nil && m.StoreDir != nil {
		return *m.StoreDir
	}
	return ""
}

type SwapStoreResponse struct {
	Error            *Error  `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	PreviousStoreDir *string `protobuf:"bytes,2,opt,name=previous_store_dir" json:"previous_store_dir,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SwapStoreResponse) Reset()         { *m = SwapStoreResponse{} }
func (m *SwapStoreResponse) String() string { return proto.CompactTextString(m) }
func (*SwapStoreResponse) ProtoMessage()    {}

func (m *SwapStoreResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *SwapStoreResponse) GetPreviousStoreDir() string {
	if m != nil && m.PreviousStoreDir != nil {
		return *m.PreviousStoreDir
	}
	return ""
}

type RollbackStoreRequest struct {
	StoreName        *string `protobuf:"bytes,1,req,name=store_name" json:"store_name,omitempty"`
	PushVersion      *int64  `protobuf:"varint,2,req,name=push_version" json:"push_version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RollbackStoreRequest) Reset()         { *m = RollbackStoreRequest{} }
func (m *RollbackStoreRequest) String() string { return proto.CompactTextString(m) }
func (*RollbackStoreRequest) ProtoMessage()    {}

func (m *RollbackStoreRequest) GetStoreName() string {
	if m != nil && m.StoreName != nil {
		return *m.StoreName
	}
	return ""
}

func (m *RollbackStoreRequest) GetPushVersion() int64 {
	if m != nil && m.PushVersion != nil {
		return *m.PushVersion
	}
	return 0
}

type RollbackStoreResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RollbackStoreResponse) Reset()         { *m = RollbackStoreResponse{} }
func (m *RollbackStoreResponse) String() string { return proto.CompactTextString(m) }
func (*RollbackStoreResponse) ProtoMessage()    {}

func (m *RollbackStoreResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type RepairJobRequest struct {
	StoreName        *string `protobuf:"bytes,1,opt,name=store_name" json:"store_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RepairJobRequest) Reset()         { *m = RepairJobRequest{} }
func (m *RepairJobRequest) String() string { return proto.CompactTextString(m) }
func (*RepairJobRequest) ProtoMessage()    {}

func (m *RepairJobRequest) GetStoreName() string {
	if m != nil && m.StoreName != nil {
		return *m.StoreName
	}
	return ""
}

type RepairJobResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RepairJobResponse) Reset()         { *m = RepairJobResponse{} }
func (m *RepairJobResponse) String() string { return proto.CompactTextString(m) }
func (*RepairJobResponse) ProtoMessage()    {}

func (m *RepairJobResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type PruneJobRequest struct {
	StoreName        *string `protobuf:"bytes,1,opt,name=store_name" json:"store_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PruneJobRequest) Reset()         { *m = PruneJobRequest{} }
func (m *PruneJobRequest) String() string { return proto.CompactTextString(m) }
func (*PruneJobRequest) ProtoMessage()    {}

func (m *PruneJobRequest) GetStoreName() string {
	if m != nil && m.StoreName != nil {
		return *m.StoreName
	}
	return ""
}

type PruneJobResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PruneJobResponse) Reset()         { *m = PruneJobResponse{} }
func (m *PruneJobResponse) String() string { return proto.CompactTextString(m) }
func (*PruneJobResponse) ProtoMessage()    {}

func (m *PruneJobResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ROStoreVersionDirMap struct {
	StoreName        *string `protobuf:"bytes,1,req,name=store_name" json:"store_name,omitempty"`
	StoreDir         *string `protobuf:"bytes,2,req,name=store_dir" json:"store_dir,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ROStoreVersionDirMap) Reset()         { *m = ROStoreVersionDirMap{} }
func (m *ROStoreVersionDirMap) String() string { return proto.CompactTextString(m) }
func (*ROStoreVersionDirMap) ProtoMessage()    {}

func (m *ROStoreVersionDirMap) GetStoreName() string {
	if m != nil && m.StoreName != nil {
		return *m.StoreName
	}
	return ""
}

func (m *ROStoreVersionDirMap) GetStoreDir() string {
	if m != nil && m.StoreDir != nil {
		return *m.StoreDir
	}
	return ""
}

type GetROMaxVersionDirRequest struct {
	StoreName        []string `protobuf:"bytes,1,rep,name=store_name" json:"store_name,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetROMaxVersionDirRequest) Reset()         { *m = GetROMaxVersionDirRequest{} }
func (m *GetROMaxVersionDirRequest) String() string { return proto.CompactTextString(m) }
func (*GetROMaxVersionDirRequest) ProtoMessage()    {}

func (m *GetROMaxVersionDirRequest) GetStoreName() []string {
	if m != nil {
		return m.StoreName
	}
	return nil
}

type GetROMaxVersionDirResponse struct {
	RoStoreVersions  []*ROStoreVersionDirMap `protobuf:"bytes,1,rep,name=ro_store_versions" json:"ro_store_versions,omitempty"`
	Error            *Error                  `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *GetROMaxVersionDirResponse) Reset()         { *m = GetROMaxVersionDirResponse{} }
func (m *GetROMaxVersionDirResponse) String() string { return proto.CompactTextString(m) }
func (*GetROMaxVersionDirResponse) ProtoMessage()    {}

func (m *GetROMaxVersionDirResponse) GetRoStoreVersions() []*ROStoreVersionDirMap {
	if m != nil {
		return m.RoStoreVersions
	}
	return nil
}

func (m *GetROMaxVersionDirResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetROCurrentVersionDirRequest struct {
	StoreName        []string `protobuf:"bytes,1,rep,name=store_name" json:"store_name,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetROCurrentVersionDirRequest) Reset()         { *m = GetROCurrentVersionDirRequest{} }
func (m *GetROCurrentVersionDirRequest) String() string { return proto.CompactTextString(m) }
func (*GetROCurrentVersionDirRequest) ProtoMessage()    {}

func (m *GetROCurrentVersionDirRequest) GetStoreName() []string {
	if m != nil {
		return m.StoreName
	}
	return nil
}

type GetROCurrentVersionDirResponse struct {
	RoStoreVersions  []*ROStoreVersionDirMap `protobuf:"bytes,1,rep,name=ro_store_versions" json:"ro_store_versions,omitempty"`
	Error            *Error                  `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *GetROCurrentVersionDirResponse) Reset()         { *m = GetROCurrentVersionDirResponse{} }
func (m *GetROCurrentVersionDirResponse) String() string { return proto.CompactTextString(m) }
func (*GetROCurrentVersionDirResponse) ProtoMessage()    {}

func (m *GetROCurrentVersionDirResponse) GetRoStoreVersions() []*ROStoreVersionDirMap {
	if m != nil {
		return m.RoStoreVersions
	}
	return nil
}

func (m *GetROCurrentVersionDirResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetROStorageFormatRequest struct {
	StoreName        []string `protobuf:"bytes,1,rep,name=store_name" json:"store_name,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetROStorageFormatRequest) Reset()         { *m = GetROStorageFormatRequest{} }
func (m *GetROStorageFormatRequest) String() string { return proto.CompactTextString(m) }
func (*GetROStorageFormatRequest) ProtoMessage()    {}

func (m *GetROStorageFormatRequest) GetStoreName() []string {
	if m != nil {
		return m.StoreName
	}
	return nil
}

type GetROStorageFormatResponse struct {
	RoStoreVersions  []*ROStoreVersionDirMap `protobuf:"bytes,1,rep,name=ro_store_versions" json:"ro_store_versions,omitempty"`
	Error            *Error                  `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *GetROStorageFormatResponse) Reset()         { *m = GetROStorageFormatResponse{} }
func (m *GetROStorageFormatResponse) String() string { return proto.CompactTextString(m) }
func (*GetROStorageFormatResponse) ProtoMessage()    {}

func (m *GetROStorageFormatResponse) GetRoStoreVersions() []*ROStoreVersionDirMap {
	if m != nil {
		return m.RoStoreVersions
	}
	return nil
}

func (m *GetROStorageFormatResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type FailedFetchStoreRequest struct {
	StoreName        *string `protobuf:"bytes,1,req,name=store_name" json:"store_name,omitempty"`
	StoreDir         *string `protobuf:"bytes,2,req,name=store_dir" json:"store_dir,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FailedFetchStoreRequest) Reset()         { *m = FailedFetchStoreRequest{} }
func (m *FailedFetchStoreRequest) String() string { return proto.CompactTextString(m) }
func (*FailedFetchStoreRequest) ProtoMessage()    {}

func (m *FailedFetchStoreRequest) GetStoreName() string {
	if m != nil && m.StoreName != nil {
		return *m.StoreName
	}
	return ""
}

func (m *FailedFetchStoreRequest) GetStoreDir() string {
	if m != nil && m.StoreDir != nil {
		return *m.StoreDir
	}
	return ""
}

type FailedFetchStoreResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FailedFetchStoreResponse) Reset()         { *m = FailedFetchStoreResponse{} }
func (m *FailedFetchStoreResponse) String() string { return proto.CompactTextString(m) }
func (*FailedFetchStoreResponse) ProtoMessage()    {}

func (m *FailedFetchStoreResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type RebalanceStateChangeRequest struct {
	RebalanceTaskList     []*RebalanceTaskInfoMap `protobuf:"bytes,1,rep,name=rebalance_task_list" json:"rebalance_task_list,omitempty"`
	ClusterString         *string                 `protobuf:"bytes,2,req,name=cluster_string" json:"cluster_string,omitempty"`
	StoresString          *string                 `protobuf:"bytes,3,req,name=stores_string" json:"stores_string,omitempty"`
	SwapRo                *bool                   `protobuf:"varint,4,req,name=swap_ro" json:"swap_ro,omitempty"`
	ChangeClusterMetadata *bool                   `protobuf:"varint,5,req,name=change_cluster_metadata" json:"change_cluster_metadata,omitempty"`
	ChangeRebalanceState  *bool                   `protobuf:"varint,6,req,name=change_rebalance_state" json:"change_rebalance_state,omitempty"`
	Rollback              *bool                   `protobuf:"varint,7,req,name=rollback" json:"rollback,omitempty"`
	XXX_unrecognized      []byte                  `json:"-"`
}

func (m *RebalanceStateChangeRequest) Reset()         { *m = RebalanceStateChangeRequest{} }
func (m *RebalanceStateChangeRequest) String() string { return proto.CompactTextString(m) }
func (*RebalanceStateChangeRequest) ProtoMessage()    {}

func (m *RebalanceStateChangeRequest) GetRebalanceTaskList() []*RebalanceTaskInfoMap {
	if m != nil {
		return m.RebalanceTaskList
	}
	return nil
}

func (m *RebalanceStateChangeRequest) GetClusterString() string {
	if m != nil && m.ClusterString != nil {
		return *m.ClusterString
	}
	return ""
}

func (m *RebalanceStateChangeRequest) GetStoresString() string {
	if m != nil && m.StoresString != nil {
		return *m.StoresString
	}
	return ""
}

func (m *RebalanceStateChangeRequest) GetSwapRo() bool {
	if m != nil && m.SwapRo != nil {
		return *m.SwapRo
	}
	return false
}

func (m *RebalanceStateChangeRequest) GetChangeClusterMetadata() bool {
	if m != nil && m.ChangeClusterMetadata != nil {
		return *m.ChangeClusterMetadata
	}
	return false
}

func (m *RebalanceStateChangeRequest) GetChangeRebalanceState() bool {
	if m != nil && m.ChangeRebalanceState != nil {
		return *m.ChangeRebalanceState
	}
	return false
}

func (m *RebalanceStateChangeRequest) GetRollback() bool {
	if m != nil && m.Rollback != nil {
		return *m.Rollback
	}
	return false
}

type RebalanceStateChangeResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RebalanceStateChangeResponse) Reset()         { *m = RebalanceStateChangeResponse{} }
func (m *RebalanceStateChangeResponse) String() string { return proto.CompactTextString(m) }
func (*RebalanceStateChangeResponse) ProtoMessage()    {}

func (m *RebalanceStateChangeResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DeleteStoreRebalanceStateRequest struct {
	StoreName        *string `protobuf:"bytes,1,req,name=store_name" json:"store_name,omitempty"`
	NodeId           *int32  `protobuf:"varint,2,req,name=node_id" json:"node_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteStoreRebalanceStateRequest) Reset()         { *m = DeleteStoreRebalanceStateRequest{} }
func (m *DeleteStoreRebalanceStateRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStoreRebalanceStateRequest) ProtoMessage()    {}

func (m *DeleteStoreRebalanceStateRequest) GetStoreName() string {
	if m != nil && m.StoreName != nil {
		return *m.StoreName
	}
	return ""
}

func (m *DeleteStoreRebalanceStateRequest) GetNodeId() int32 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

type DeleteStoreRebalanceStateResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteStoreRebalanceStateResponse) Reset()         { *m = DeleteStoreRebalanceStateResponse{} }
func (m *DeleteStoreRebalanceStateResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteStoreRebalanceStateResponse) ProtoMessage()    {}

func (m *DeleteStoreRebalanceStateResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type NativeBackupRequest struct {
	StoreName        *string `protobuf:"bytes,1,req,name=store_name" json:"store_name,omitempty"`
	BackupDir        *string `protobuf:"bytes,2,req,name=backup_dir" json:"backup_dir,omitempty"`
	VerifyFiles      *bool   `protobuf:"varint,3,req,name=verify_files" json:"verify_files,omitempty"`
	Incremental      *bool   `protobuf:"varint,4,req,name=incremental" json:"incremental,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NativeBackupRequest) Reset()         { *m = NativeBackupRequest{} }
func (m *NativeBackupRequest) String() string { return proto.CompactTextString(m) }
func (*NativeBackupRequest) ProtoMessage()    {}

func (m *NativeBackupRequest) GetStoreName() string {
	if m != nil && m.StoreName != nil {
		return *m.StoreName
	}
	return ""
}

func (m *NativeBackupRequest) GetBackupDir() string {
	if m != nil && m.BackupDir != nil {
		return *m.BackupDir
	}
	return ""
}

func (m *NativeBackupRequest) GetVerifyFiles() bool {
	if m != nil && m.VerifyFiles != nil {
		return *m.VerifyFiles
	}
	return false
}

func (m *NativeBackupRequest) GetIncremental() bool {
	if m != nil && m.Incremental != nil {
		return *m.Incremental
	}
	return false
}

type ReserveMemoryRequest struct {
	StoreName        *string `protobuf:"bytes,1,req,name=store_name" json:"store_name,omitempty"`
	SizeInMb         *int64  `protobuf:"varint,2,req,name=size_in_mb" json:"size_in_mb,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReserveMemoryRequest) Reset()         { *m = ReserveMemoryRequest{} }
func (m *ReserveMemoryRequest) String() string { return proto.CompactTextString(m) }
func (*ReserveMemoryRequest) ProtoMessage()    {}

func (m *ReserveMemoryRequest) GetStoreName() string {
	if m != nil && m.StoreName != nil {
		return *m.StoreName
	}
	return ""
}

func (m *ReserveMemoryRequest) GetSizeInMb() int64 {
	if m != nil && m.SizeInMb != nil {
		return *m.SizeInMb
	}
	return 0
}

type ReserveMemoryResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReserveMemoryResponse) Reset()         { *m = ReserveMemoryResponse{} }
func (m *ReserveMemoryResponse) String() string { return proto.CompactTextString(m) }
func (*ReserveMemoryResponse) ProtoMessage()    {}

func (m *ReserveMemoryResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type VoldemortAdminRequest struct {
	Type                   *AdminRequestType              `protobuf:"varint,1,req,name=type,enum=voldemort.AdminRequestType" json:"type,omitempty"`
	GetMetadata            *GetMetadataRequest            `protobuf:"bytes,2,opt,name=get_metadata" json:"get_metadata,omitempty"`
	UpdateMetadata         *UpdateMetadataRequest         `protobuf:"bytes,3,opt,name=update_metadata" json:"update_metadata,omitempty"`
	UpdatePartitionEntries *UpdatePartitionEntriesRequest `protobuf:"bytes,4,opt,name=update_partition_entries" json:"update_partition_entries,omitempty"`
	FetchPartitionEntries  *FetchPartitionEntriesRequest  `protobuf:"bytes,5,opt,name=fetch_partition_entries" json:"fetch_partition_entries,omitempty"`
	DeletePartitionEntries *DeletePartitionEntriesRequest `protobuf:"bytes,6,opt,name=delete_partition_entries" json:"delete_partition_entries,omitempty"`
	InitiateFetchAndUpdate *InitiateFetchAndUpdateRequest `protobuf:"bytes,7,opt,name=initiate_fetch_and_update" json:"initiate_fetch_and_update,omitempty"`
	AsyncOperationStatus   *AsyncOperationStatusRequest   `protobuf:"bytes,8,opt,name=async_operation_status" json:"async_operation_status,omitempty"`
	InitiateRebalanceNode  *InitiateRebalanceNodeRequest  `protobuf:"bytes,9,opt,name=initiate_rebalance_node" json:"initiate_rebalance_node,omitempty"`
	AsyncOperationStop     *AsyncOperationStopRequest     `protobuf:"bytes,10,opt,name=async_operation_stop" json:"async_operation_stop,omitempty"`
	AsyncOperationList     *AsyncOperationListRequest     `protobuf:"bytes,11,opt,name=async_operation_list" json:"async_operation_list,omitempty"`
	TruncateEntries        *TruncateEntriesRequest        `protobuf:"bytes,12,opt,name=truncate_entries" json:"truncate_entries,omitempty"`
	AddStore               *AddStoreRequest               `protobuf:"bytes,13,opt,name=add_store" json:"add_store,omitempty"`
	DeleteStore            *DeleteStoreRequest            `protobuf:"bytes,14,opt,name=delete_store" json:"delete_store,omitempty"`
	FetchStore             *FetchStoreRequest             `protobuf:"bytes,15,opt,name=fetch_store" json:"fetch_store,omitempty"`
	SwapStore              *SwapStoreRequest              `protobuf:"bytes,16,opt,name=swap_store" json:"swap_store,omitempty"`
	RollbackStore          *RollbackStoreRequest          `protobuf:"bytes,17,opt,name=rollback_store" json:"rollback_store,omitempty"`
	GetRoMaxVersionDir     *GetROMaxVersionDirRequest     `protobuf:"bytes,18,opt,name=get_ro_max_version_dir" json:"get_ro_max_version_dir,omitempty"`
	GetRoCurrentVersionDir *GetROCurrentVersionDirRequest `protobuf:"bytes,19,opt,name=get_ro_current_version_dir" json:"get_ro_current_version_dir,omitempty"`
	FetchPartitionFiles    *FetchPartitionFilesRequest    `protobuf:"bytes,20,opt,name=fetch_partition_files" json:"fetch_partition_files,omitempty"`
	UpdateSlopEntries      *UpdateSlopEntriesRequest      `protobuf:"bytes,22,opt,name=update_slop_entries" json:"update_slop_entries,omitempty"`
	FailedFetchStore       *FailedFetchStoreRequest       `protobuf:"bytes,24,opt,name=failed_fetch_store" json:"failed_fetch_store,omitempty"`
	GetRoStorageFormat     *GetROStorageFormatRequest     `protobuf:"bytes,25,opt,name=get_ro_storage_format" json:"get_ro_storage_format,omitempty"`
	RebalanceStateChange   *RebalanceStateChangeRequest   `protobuf:"bytes,26,opt,name=rebalance_state_change" json:"rebalance_state_change,omitempty"`
	RepairJob              *RepairJobRequest              `protobuf:"bytes,27,opt,name=repair_job" json:"repair_job,omitempty"`
	// optional InitiateRebalanceNodeOnDonorRequest initiate_rebalance_node_on_donor = 28;
	DeleteStoreRebalanceState *DeleteStoreRebalanceStateRequest `protobuf:"bytes,29,opt,name=delete_store_rebalance_state" json:"delete_store_rebalance_state,omitempty"`
	NativeBackup              *NativeBackupRequest              `protobuf:"bytes,30,opt,name=native_backup" json:"native_backup,omitempty"`
	ReserveMemory             *ReserveMemoryRequest             `protobuf:"bytes,31,opt,name=reserve_memory" json:"reserve_memory,omitempty"`
	PruneJob                  *PruneJobRequest                  `protobuf:"bytes,32,opt,name=prune_job" json:"prune_job,omitempty"`
	XXX_unrecognized          []byte                            `json:"-"`
}

func (m *VoldemortAdminRequest) Reset()         { *m = VoldemortAdminRequest{} }
func (m *VoldemortAdminRequest) String() string { return proto.CompactTextString(m) }
func (*VoldemortAdminRequest) ProtoMessage()    {}

func (m *VoldemortAdminRequest) GetType() AdminRequestType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return AdminRequestType_GET_METADATA
}

func (m *VoldemortAdminRequest) GetGetMetadata() *GetMetadataRequest {
	if m != nil {
		return m.GetMetadata
	}
	return nil
}

func (m *VoldemortAdminRequest) GetUpdateMetadata() *UpdateMetadataRequest {
	if m != nil {
		return m.UpdateMetadata
	}
	return nil
}

func (m *VoldemortAdminRequest) GetUpdatePartitionEntries() *UpdatePartitionEntriesRequest {
	if m != nil {
		return m.UpdatePartitionEntries
	}
	return nil
}

func (m *VoldemortAdminRequest) GetFetchPartitionEntries() *FetchPartitionEntriesRequest {
	if m != nil {
		return m.FetchPartitionEntries
	}
	return nil
}

func (m *VoldemortAdminRequest) GetDeletePartitionEntries() *DeletePartitionEntriesRequest {
	if m != nil {
		return m.DeletePartitionEntries
	}
	return nil
}

func (m *VoldemortAdminRequest) GetInitiateFetchAndUpdate() *InitiateFetchAndUpdateRequest {
	if m != nil {
		return m.InitiateFetchAndUpdate
	}
	return nil
}

func (m *VoldemortAdminRequest) GetAsyncOperationStatus() *AsyncOperationStatusRequest {
	if m != nil {
		return m.AsyncOperationStatus
	}
	return nil
}

func (m *VoldemortAdminRequest) GetInitiateRebalanceNode() *InitiateRebalanceNodeRequest {
	if m != nil {
		return m.InitiateRebalanceNode
	}
	return nil
}

func (m *VoldemortAdminRequest) GetAsyncOperationStop() *AsyncOperationStopRequest {
	if m != nil {
		return m.AsyncOperationStop
	}
	return nil
}

func (m *VoldemortAdminRequest) GetAsyncOperationList() *AsyncOperationListRequest {
	if m != nil {
		return m.AsyncOperationList
	}
	return nil
}

func (m *VoldemortAdminRequest) GetTruncateEntries() *TruncateEntriesRequest {
	if m != nil {
		return m.TruncateEntries
	}
	return nil
}

func (m *VoldemortAdminRequest) GetAddStore() *AddStoreRequest {
	if m != nil {
		return m.AddStore
	}
	return nil
}

func (m *VoldemortAdminRequest) GetDeleteStore() *DeleteStoreRequest {
	if m != nil {
		return m.DeleteStore
	}
	return nil
}

func (m *VoldemortAdminRequest) GetFetchStore() *FetchStoreRequest {
	if m != nil {
		return m.FetchStore
	}
	return nil
}

func (m *VoldemortAdminRequest) GetSwapStore() *SwapStoreRequest {
	if m != nil {
		return m.SwapStore
	}
	return nil
}

func (m *VoldemortAdminRequest) GetRollbackStore() *RollbackStoreRequest {
	if m != nil {
		return m.RollbackStore
	}
	return nil
}

func (m *VoldemortAdminRequest) GetGetRoMaxVersionDir() *GetROMaxVersionDirRequest {
	if m != nil {
		return m.GetRoMaxVersionDir
	}
	return nil
}

func (m *VoldemortAdminRequest) GetGetRoCurrentVersionDir() *GetROCurrentVersionDirRequest {
	if m != nil {
		return m.GetRoCurrentVersionDir
	}
	return nil
}

func (m *VoldemortAdminRequest) GetFetchPartitionFiles() *FetchPartitionFilesRequest {
	if m != nil {
		return m.FetchPartitionFiles
	}
	return nil
}

func (m *VoldemortAdminRequest) GetUpdateSlopEntries() *UpdateSlopEntriesRequest {
	if m != nil {
		return m.UpdateSlopEntries
	}
	return nil
}

func (m *VoldemortAdminRequest) GetFailedFetchStore() *FailedFetchStoreRequest {
	if m != nil {
		return m.FailedFetchStore
	}
	return nil
}

func (m *VoldemortAdminRequest) GetGetRoStorageFormat() *GetROStorageFormatRequest {
	if m != nil {
		return m.GetRoStorageFormat
	}
	return nil
}

func (m *VoldemortAdminRequest) GetRebalanceStateChange() *RebalanceStateChangeRequest {
	if m != nil {
		return m.RebalanceStateChange
	}
	return nil
}

func (m *VoldemortAdminRequest) GetRepairJob() *RepairJobRequest {
	if m != nil {
		return m.RepairJob
	}
	return nil
}

func (m *VoldemortAdminRequest) GetDeleteStoreRebalanceState() *DeleteStoreRebalanceStateRequest {
	if m != nil {
		return m.DeleteStoreRebalanceState
	}
	return nil
}

func (m *VoldemortAdminRequest) GetNativeBackup() *NativeBackupRequest {
	if m != nil {
		return m.NativeBackup
	}
	return nil
}

func (m *VoldemortAdminRequest) GetReserveMemory() *ReserveMemoryRequest {
	if m != nil {
		return m.ReserveMemory
	}
	return nil
}

func (m *VoldemortAdminRequest) GetPruneJob() *PruneJobRequest {
	if m != nil {
		return m.PruneJob
	}
	return nil
}

func init() {
	proto.RegisterEnum("voldemort.AdminRequestType", AdminRequestType_name, AdminRequestType_value)
}
