// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voldemort-client.proto

package voldemort

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RequestType int32

const (
	RequestType_GET         RequestType = 0
	RequestType_GET_ALL     RequestType = 1
	RequestType_PUT         RequestType = 2
	RequestType_DELETE      RequestType = 3
	RequestType_GET_VERSION RequestType = 4
)

var RequestType_name = map[int32]string{
	0: "GET",
	1: "GET_ALL",
	2: "PUT",
	3: "DELETE",
	4: "GET_VERSION",
}
var RequestType_value = map[string]int32{
	"GET":         0,
	"GET_ALL":     1,
	"PUT":         2,
	"DELETE":      3,
	"GET_VERSION": 4,
}

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}
func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (x *RequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestType_value, data, "RequestType")
	if err != nil {
		return err
	}
	*x = RequestType(value)
	return nil
}
func (RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type ClockEntry struct {
	NodeId           *int32 `protobuf:"varint,1,req,name=node_id,json=nodeId" json:"node_id,omitempty"`
	Version          *int64 `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ClockEntry) Reset()                    { *m = ClockEntry{} }
func (m *ClockEntry) String() string            { return proto.CompactTextString(m) }
func (*ClockEntry) ProtoMessage()               {}
func (*ClockEntry) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *ClockEntry) GetNodeId() int32 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *ClockEntry) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type VectorClock struct {
	Entries          []*ClockEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	Timestamp        *int64        `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *VectorClock) Reset()                    { *m = VectorClock{} }
func (m *VectorClock) String() string            { return proto.CompactTextString(m) }
func (*VectorClock) ProtoMessage()               {}
func (*VectorClock) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *VectorClock) GetEntries() []*ClockEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *VectorClock) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type Versioned struct {
	Value            []byte       `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	Version          *VectorClock `protobuf:"bytes,2,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Versioned) Reset()                    { *m = Versioned{} }
func (m *Versioned) String() string            { return proto.CompactTextString(m) }
func (*Versioned) ProtoMessage()               {}
func (*Versioned) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *Versioned) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Versioned) GetVersion() *VectorClock {
	if m != nil {
		return m.Version
	}
	return nil
}

type Error struct {
	ErrorCode        *int32  `protobuf:"varint,1,req,name=error_code,json=errorCode" json:"error_code,omitempty"`
	ErrorMessage     *string `protobuf:"bytes,2,req,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *Error) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *Error) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

type KeyedVersions struct {
	Key              []byte       `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Versions         []*Versioned `protobuf:"bytes,2,rep,name=versions" json:"versions,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *KeyedVersions) Reset()                    { *m = KeyedVersions{} }
func (m *KeyedVersions) String() string            { return proto.CompactTextString(m) }
func (*KeyedVersions) ProtoMessage()               {}
func (*KeyedVersions) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *KeyedVersions) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyedVersions) GetVersions() []*Versioned {
	if m != nil {
		return m.Versions
	}
	return nil
}

type GetRequest struct {
	Key              []byte `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Transforms       []byte `protobuf:"bytes,2,opt,name=transforms" json:"transforms,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetRequest) GetTransforms() []byte {
	if m != nil {
		return m.Transforms
	}
	return nil
}

type GetResponse struct {
	Versioned        []*Versioned `protobuf:"bytes,1,rep,name=versioned" json:"versioned,omitempty"`
	Error            *Error       `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *GetResponse) GetVersioned() []*Versioned {
	if m != nil {
		return m.Versioned
	}
	return nil
}

func (m *GetResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetVersionResponse struct {
	Versions         []*VectorClock `protobuf:"bytes,1,rep,name=versions" json:"versions,omitempty"`
	Error            *Error         `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GetVersionResponse) Reset()                    { *m = GetVersionResponse{} }
func (m *GetVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetVersionResponse) ProtoMessage()               {}
func (*GetVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *GetVersionResponse) GetVersions() []*VectorClock {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *GetVersionResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetAllRequest struct {
	Keys             [][]byte                         `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	Transforms       []*GetAllRequest_GetAllTransform `protobuf:"bytes,2,rep,name=transforms" json:"transforms,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *GetAllRequest) Reset()                    { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()               {}
func (*GetAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *GetAllRequest) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *GetAllRequest) GetTransforms() []*GetAllRequest_GetAllTransform {
	if m != nil {
		return m.Transforms
	}
	return nil
}

type GetAllRequest_GetAllTransform struct {
	Key              []byte `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Transform        []byte `protobuf:"bytes,2,req,name=transform" json:"transform,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetAllRequest_GetAllTransform) Reset()         { *m = GetAllRequest_GetAllTransform{} }
func (m *GetAllRequest_GetAllTransform) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest_GetAllTransform) ProtoMessage()    {}
func (*GetAllRequest_GetAllTransform) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{8, 0}
}

func (m *GetAllRequest_GetAllTransform) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetAllRequest_GetAllTransform) GetTransform() []byte {
	if m != nil {
		return m.Transform
	}
	return nil
}

type GetAllResponse struct {
	Values           []*KeyedVersions `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	Error            *Error           `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GetAllResponse) Reset()                    { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()               {}
func (*GetAllResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *GetAllResponse) GetValues() []*KeyedVersions {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *GetAllResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type PutRequest struct {
	Key              []byte     `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Versioned        *Versioned `protobuf:"bytes,2,req,name=versioned" json:"versioned,omitempty"`
	Transforms       []byte     `protobuf:"bytes,3,opt,name=transforms" json:"transforms,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *PutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PutRequest) GetVersioned() *Versioned {
	if m != nil {
		return m.Versioned
	}
	return nil
}

func (m *PutRequest) GetTransforms() []byte {
	if m != nil {
		return m.Transforms
	}
	return nil
}

type PutResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *PutResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DeleteRequest struct {
	Key              []byte       `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Version          *VectorClock `protobuf:"bytes,2,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *DeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DeleteRequest) GetVersion() *VectorClock {
	if m != nil {
		return m.Version
	}
	return nil
}

type DeleteResponse struct {
	Success          *bool  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Error            *Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *DeleteResponse) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *DeleteResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type VoldemortRequest struct {
	Type             *RequestType   `protobuf:"varint,1,req,name=type,enum=voldemort.RequestType" json:"type,omitempty"`
	ShouldRoute      *bool          `protobuf:"varint,2,req,name=should_route,json=shouldRoute,def=0" json:"should_route,omitempty"`
	Store            *string        `protobuf:"bytes,3,req,name=store" json:"store,omitempty"`
	Get              *GetRequest    `protobuf:"bytes,4,opt,name=get" json:"get,omitempty"`
	GetAll           *GetAllRequest `protobuf:"bytes,5,opt,name=getAll" json:"getAll,omitempty"`
	Put              *PutRequest    `protobuf:"bytes,6,opt,name=put" json:"put,omitempty"`
	Delete           *DeleteRequest `protobuf:"bytes,7,opt,name=delete" json:"delete,omitempty"`
	RequestRouteType *int32         `protobuf:"varint,8,opt,name=requestRouteType" json:"requestRouteType,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *VoldemortRequest) Reset()                    { *m = VoldemortRequest{} }
func (m *VoldemortRequest) String() string            { return proto.CompactTextString(m) }
func (*VoldemortRequest) ProtoMessage()               {}
func (*VoldemortRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

const Default_VoldemortRequest_ShouldRoute bool = false

func (m *VoldemortRequest) GetType() RequestType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RequestType_GET
}

func (m *VoldemortRequest) GetShouldRoute() bool {
	if m != nil && m.ShouldRoute != nil {
		return *m.ShouldRoute
	}
	return Default_VoldemortRequest_ShouldRoute
}

func (m *VoldemortRequest) GetStore() string {
	if m != nil && m.Store != nil {
		return *m.Store
	}
	return ""
}

func (m *VoldemortRequest) GetGet() *GetRequest {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *VoldemortRequest) GetGetAll() *GetAllRequest {
	if m != nil {
		return m.GetAll
	}
	return nil
}

func (m *VoldemortRequest) GetPut() *PutRequest {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *VoldemortRequest) GetDelete() *DeleteRequest {
	if m != nil {
		return m.Delete
	}
	return nil
}

func (m *VoldemortRequest) GetRequestRouteType() int32 {
	if m != nil && m.RequestRouteType != nil {
		return *m.RequestRouteType
	}
	return 0
}

func init() {
	proto.RegisterType((*ClockEntry)(nil), "voldemort.ClockEntry")
	proto.RegisterType((*VectorClock)(nil), "voldemort.VectorClock")
	proto.RegisterType((*Versioned)(nil), "voldemort.Versioned")
	proto.RegisterType((*Error)(nil), "voldemort.Error")
	proto.RegisterType((*KeyedVersions)(nil), "voldemort.KeyedVersions")
	proto.RegisterType((*GetRequest)(nil), "voldemort.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "voldemort.GetResponse")
	proto.RegisterType((*GetVersionResponse)(nil), "voldemort.GetVersionResponse")
	proto.RegisterType((*GetAllRequest)(nil), "voldemort.GetAllRequest")
	proto.RegisterType((*GetAllRequest_GetAllTransform)(nil), "voldemort.GetAllRequest.GetAllTransform")
	proto.RegisterType((*GetAllResponse)(nil), "voldemort.GetAllResponse")
	proto.RegisterType((*PutRequest)(nil), "voldemort.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "voldemort.PutResponse")
	proto.RegisterType((*DeleteRequest)(nil), "voldemort.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "voldemort.DeleteResponse")
	proto.RegisterType((*VoldemortRequest)(nil), "voldemort.VoldemortRequest")
	proto.RegisterEnum("voldemort.RequestType", RequestType_name, RequestType_value)
}

func init() { proto.RegisterFile("voldemort-client.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 737 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xfd, 0x1c, 0xe7, 0x77, 0x9c, 0xb4, 0xd6, 0xaa, 0xed, 0x67, 0xa1, 0x82, 0x22, 0x23, 0x81,
	0x55, 0x89, 0x50, 0x45, 0xe2, 0x86, 0x0b, 0x50, 0x7f, 0xac, 0xb4, 0x6a, 0x81, 0x6a, 0x13, 0x72,
	0x85, 0x14, 0x85, 0x78, 0x5a, 0x42, 0x9d, 0xac, 0xf1, 0x6e, 0x22, 0xe5, 0xad, 0x78, 0x24, 0x1e,
	0x05, 0xed, 0x7a, 0x1d, 0xdb, 0x4d, 0x0b, 0xe5, 0xce, 0x33, 0x73, 0x72, 0xe6, 0xec, 0xf1, 0xf1,
	0x06, 0xf6, 0x96, 0x2c, 0x0c, 0x70, 0xc6, 0x62, 0xf1, 0x6a, 0x12, 0x4e, 0x71, 0x2e, 0x3a, 0x51,
	0xcc, 0x04, 0x23, 0x8d, 0x75, 0xdf, 0x7d, 0x0f, 0x70, 0x12, 0xb2, 0xc9, 0xad, 0x3f, 0x17, 0xf1,
	0x8a, 0xfc, 0x0f, 0xb5, 0x39, 0x0b, 0x70, 0x34, 0x0d, 0x1c, 0xa3, 0x5d, 0xf2, 0x2a, 0xb4, 0x2a,
	0xcb, 0xf3, 0x80, 0x38, 0x50, 0x5b, 0x62, 0xcc, 0xa7, 0x6c, 0xee, 0x94, 0xda, 0x25, 0xcf, 0xa4,
	0x69, 0xe9, 0x7e, 0x01, 0x6b, 0x88, 0x13, 0xc1, 0x62, 0x45, 0x43, 0x5e, 0x43, 0x0d, 0xe7, 0x22,
	0x9e, 0x22, 0x77, 0x8c, 0xb6, 0xe9, 0x59, 0xdd, 0xdd, 0xce, 0x7a, 0x59, 0x27, 0xdb, 0x44, 0x53,
	0x14, 0xd9, 0x87, 0x86, 0x98, 0xce, 0x90, 0x8b, 0xf1, 0x2c, 0x72, 0x4a, 0x6d, 0xc3, 0x33, 0x69,
	0xd6, 0x70, 0xfb, 0xd0, 0x18, 0x26, 0x8b, 0x30, 0x20, 0x3b, 0x50, 0x59, 0x8e, 0xc3, 0x05, 0x2a,
	0x6d, 0x4d, 0x9a, 0x14, 0xe4, 0xb0, 0x28, 0xcd, 0xea, 0xee, 0xe5, 0x36, 0xe6, 0xa4, 0x65, 0x92,
	0x2f, 0xa0, 0xe2, 0xc7, 0x31, 0x8b, 0xc9, 0x53, 0x00, 0x94, 0x0f, 0xa3, 0x09, 0x0b, 0x50, 0x9f,
	0xb8, 0xa1, 0x3a, 0x27, 0x2c, 0x40, 0xf2, 0x1c, 0x5a, 0xc9, 0x78, 0x86, 0x9c, 0x8f, 0x6f, 0x50,
	0xf1, 0x37, 0x68, 0x53, 0x35, 0x3f, 0x24, 0x3d, 0xb7, 0x0f, 0xad, 0x0b, 0x5c, 0x61, 0xa0, 0x65,
	0x72, 0x62, 0x83, 0x79, 0x8b, 0x2b, 0xad, 0x51, 0x3e, 0x92, 0x43, 0xa8, 0xeb, 0xd5, 0xdc, 0x29,
	0x29, 0x53, 0x76, 0x0a, 0x12, 0xf5, 0xf9, 0xe8, 0x1a, 0xe5, 0xbe, 0x03, 0xe8, 0xa1, 0xa0, 0xf8,
	0x63, 0x81, 0x5c, 0x64, 0x8c, 0x46, 0xca, 0xf8, 0x0c, 0x40, 0xc4, 0xe3, 0x39, 0xbf, 0x66, 0xf1,
	0x8c, 0x2b, 0xd7, 0x9a, 0x34, 0xd7, 0x71, 0xa7, 0x60, 0xa9, 0xdf, 0xf3, 0x88, 0xcd, 0x39, 0x92,
	0x2e, 0x34, 0x96, 0xe9, 0x16, 0xfd, 0x5a, 0xee, 0x57, 0x90, 0xc1, 0xc8, 0x0b, 0xa8, 0xa8, 0x73,
	0x2a, 0x76, 0xab, 0x6b, 0xe7, 0xf0, 0xca, 0x3c, 0x9a, 0x8c, 0xdd, 0x08, 0x48, 0x0f, 0x85, 0xa6,
	0xc8, 0x6d, 0xcc, 0x8e, 0x9c, 0x2c, 0x7c, 0xe8, 0xad, 0xac, 0x71, 0x8f, 0xde, 0xf8, 0xd3, 0x80,
	0x56, 0x0f, 0xc5, 0x51, 0x18, 0xa6, 0x06, 0x11, 0x28, 0xdf, 0xe2, 0x2a, 0xd9, 0xd4, 0xa4, 0xea,
	0x99, 0x9c, 0xdd, 0xb1, 0x48, 0x6a, 0xf0, 0x72, 0x94, 0x05, 0x06, 0x5d, 0x0d, 0xd2, 0x1f, 0xe4,
	0xcd, 0x7c, 0x72, 0x04, 0xdb, 0x77, 0xc6, 0xf7, 0xbc, 0x63, 0x19, 0xe3, 0x74, 0xac, 0x72, 0xd2,
	0xa4, 0x59, 0xc3, 0xfd, 0x0e, 0x5b, 0xe9, 0x3e, 0x6d, 0xd0, 0x21, 0x54, 0x55, 0x7c, 0x53, 0x7b,
	0x9c, 0x9c, 0xb4, 0x42, 0x9e, 0xa8, 0xc6, 0x3d, 0xda, 0x9e, 0x18, 0xe0, 0x6a, 0xb1, 0x99, 0x9d,
	0xb5, 0xd2, 0x42, 0x18, 0x92, 0x2f, 0xe6, 0xaf, 0x61, 0x28, 0xe6, 0xcd, 0xdc, 0xc8, 0xdb, 0x1b,
	0xb0, 0xd4, 0x4e, 0x7d, 0xb8, 0xb5, 0x54, 0xe3, 0xcf, 0x52, 0xfb, 0xd0, 0x3a, 0xc5, 0x10, 0x05,
	0x3e, 0xac, 0xf6, 0xdf, 0xbf, 0x6e, 0x0a, 0x5b, 0x29, 0xa9, 0x96, 0xe3, 0x40, 0x8d, 0x2f, 0x26,
	0x13, 0xe4, 0x5c, 0x31, 0xd7, 0x69, 0x5a, 0x3e, 0xda, 0xd3, 0x5f, 0x25, 0xb0, 0x87, 0xe9, 0x28,
	0x15, 0x7b, 0x00, 0x65, 0xb1, 0x8a, 0x92, 0x7b, 0x63, 0xab, 0xa0, 0x4b, 0x23, 0x06, 0xab, 0x08,
	0xa9, 0xc2, 0x10, 0x0f, 0x9a, 0xfc, 0x1b, 0x5b, 0x84, 0xc1, 0x28, 0x66, 0x0b, 0x91, 0xdc, 0x24,
	0xf5, 0xb7, 0x95, 0xeb, 0x71, 0xc8, 0x91, 0x5a, 0xc9, 0x88, 0xca, 0x89, 0xbc, 0xe4, 0xb8, 0x60,
	0x31, 0x3a, 0xa6, 0xba, 0x6c, 0x92, 0x82, 0xbc, 0x04, 0xf3, 0x06, 0x85, 0x53, 0x56, 0x32, 0x77,
	0x8b, 0x31, 0xd6, 0xdb, 0xa8, 0x44, 0xc8, 0x5c, 0xdd, 0xa8, 0xa4, 0x39, 0x15, 0x85, 0x75, 0x1e,
	0x8a, 0x3c, 0xd5, 0x38, 0x49, 0x1d, 0x2d, 0x84, 0x53, 0xdd, 0xa0, 0xce, 0x52, 0x44, 0x25, 0x42,
	0x52, 0x07, 0xca, 0x58, 0xa7, 0xb6, 0x41, 0x5d, 0x78, 0x8d, 0x54, 0xe3, 0xc8, 0x01, 0xd8, 0xb1,
	0x6e, 0xc9, 0xb3, 0x49, 0x3f, 0x9c, 0x7a, 0xdb, 0xf0, 0x2a, 0x74, 0xa3, 0x7f, 0x70, 0x0e, 0x56,
	0xce, 0x36, 0x52, 0x03, 0xb3, 0xe7, 0x0f, 0xec, 0xff, 0x88, 0x05, 0xb5, 0x9e, 0x3f, 0x18, 0x1d,
	0x5d, 0x5e, 0xda, 0x86, 0xec, 0x5e, 0x7d, 0x1e, 0xd8, 0x25, 0x02, 0x50, 0x3d, 0xf5, 0x2f, 0xfd,
	0x81, 0x6f, 0x9b, 0x64, 0x1b, 0x2c, 0x89, 0x18, 0xfa, 0xb4, 0x7f, 0xfe, 0xe9, 0xa3, 0x5d, 0x3e,
	0xf6, 0x60, 0x3f, 0x53, 0x96, 0xff, 0xe3, 0x9b, 0xb0, 0xb0, 0x13, 0x7d, 0x3d, 0xae, 0x0e, 0xaf,
	0x64, 0x75, 0x66, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xff, 0xae, 0x75, 0x21, 0x07, 0x00,
	0x00,
}
